import type { Community, HackerHouse, POAP, SuggestedBuilder } from "@/lib/types"

// Real data pulled from the live DB (Dex / @dex) — frozen here so the pitch deck
// renders the actual product components without auth or network calls.

const dexPoaps: POAP[] = [
  { id: "7582104", name: "ETHGlobal Cannes 2026 Hacker", image_url: "https://assets.poap.xyz/20b5da39-6502-45a0-a9d8-161f61cdb95f.png", event_date: "02-Apr-2026" },
  { id: "7579152", name: "🦞 OpenClaw Onchain Meetup @ EthCC Cannes 2026", image_url: "https://assets.poap.xyz/80184c38-7fdf-4dca-b7f9-dc4a435068c7.gif", event_date: "30-Mar-2026" },
  { id: "7579146", name: "EthCC [9]", image_url: "https://assets.poap.xyz/094a05c5-973b-42c2-9f9c-f55c3e2df02b.gif", event_date: "29-Mar-2026" },
  { id: "7579078", name: "Arbitrum DAO Morning Run — EthCC 2026", image_url: "https://assets.poap.xyz/832f8943-b9d9-4217-bea6-38f33e1b858b.webp", event_date: "30-Mar-2026" },
  { id: "7579117", name: "Nethermind @ EthCC[9]", image_url: "https://assets.poap.xyz/0ff60436-183d-4693-b37e-68d10cb71aaf.gif", event_date: "29-Mar-2026" },
]

export const dexBuilder: SuggestedBuilder = {
  id: "048c5f94-d50b-4330-bd8f-eaad6f3efb96",
  privy_id: "demo",
  handle: "dex",
  bio: "Serial builder and product founder. Building the protocol layer for hacker houses and on-chain collaboration. Shipping code to the world.",
  archetype: "builder",
  skills: ["smart contracts", "nextjs", "react", "typescript", "python", "ui / ux design", "openai", "javascript", "frontend"],
  wallet_address: "0xd7ed1a1FC1295A0e7Ac16b5834F152F7B6306C0e",
  email: null,
  onboarding_step: "done",
  avatar_url: "/cypher-kitten/cat-01.gif",
  languages: ["English", "Spanish", "Portuguese"],
  timezone: null,
  region: null,
  country: null,
  city: null,
  github_url: null,
  twitter_url: null,
  farcaster_url: null,
  website_url: null,
  is_verified: true,
  is_admin: false,
  talent_protocol_score: 78,
  talent_tags: [],
  talent_credentials: [],
  poaps: dexPoaps,
  seeking_skills: ["solidity", "zero knowledge", "security / auditing", "rust", "token design"],
  matching_cities: ["London"],
  featured_poaps: dexPoaps.map((p) => p.id),
  kernel_address: "0x9a3f...c0e1",
  human_passport_verified: true,
  worldid_verified: true,
  worldid_verification_level: "orb",
  banner_url: "https://znigxxyicqfuzdtdqdin.supabase.co/storage/v1/object/public/hacker-house-images/banners/did:privy:cmpqi7dsz00z50cjot0qaty8u/565e4876-c0a9-4609-a806-54b1eb269d06.gif",
  onchain_since: "2019",
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-06-14T00:00:00Z",
  match_score: 95,
  match_reasons: ["Has Smart Contracts", "Has React", "Same event: Arbitrum Open House", "Speaks Spanish", "127 POAPs verified"],
}

export const openHouseLondon: HackerHouse = {
  id: "4491cea8-20dd-419c-8ac3-a30962564ce8",
  name: "OpenHouse London",
  city: "London",
  country: "United Kingdom",
  neighborhood: "Shoreditch",
  start_date: "2026-06-20",
  end_date: "2026-06-27",
  capacity: 4,
  modality: "staking",
  price_per_person: 150,
  region: null,
  sponsor_name: null,
  images: ["https://znigxxyicqfuzdtdqdin.supabase.co/storage/v1/object/public/hacker-house-images/did:privy:cmpqi7dsz00z50cjot0qaty8u/451abbc2-72f2-4fce-9b6f-1d14cedbdfd8.jpeg"],
  includes_private_room: false,
  includes_shared_room: true,
  includes_meals: true,
  includes_workspace: true,
  includes_internet: true,
  profile_sought: ["builder", "strategist"],
  language: ["English"],
  booking_url: null,
  address: null,
  checkin_wifi_password: null,
  checkin_room_info: null,
  checkin_lockbox: null,
  checkin_notes: null,
  house_rules: null,
  status: "open",
  application_type: "curated",
  application_deadline: "2026-06-19",
  application_form_url: null,
  contract_type: "multisig",
  sponsor_community_id: null,
  event_id: null,
  event_name: "Arbitrum Open House London",
  event_url: null,
  event_start_date: "2026-06-20",
  event_end_date: "2026-06-27",
  event_timing: [],
  event_goers_only: false,
  lat: null,
  lng: null,
  created_at: "2026-06-10T00:00:00Z",
  creator: { id: "048c5f94-d50b-4330-bd8f-eaad6f3efb96", handle: "dex", archetype: "builder", avatar_url: "/cypher-kitten/cat-01.gif" },
  participants: [
    { id: "048c5f94-d50b-4330-bd8f-eaad6f3efb96", handle: "dex", archetype: "builder", avatar_url: "/cypher-kitten/cat-01.gif" },
    { id: "p2", handle: "nait", archetype: "strategist", avatar_url: "/cypher-kitten/cat-03.gif" },
    { id: "p3", handle: "vera", archetype: "visionary", avatar_url: "/cypher-kitten/cat-05.gif" },
  ],
  participants_count: 3,
  escrow_address: "0x751ea80Fae2F714812bF0317bE4df96FD3ffcfB5",
  host_safe: null,
  deposit_amount_usdc: 150,
  withdraw_date: "2026-06-27",
  house_type: "staking",
  yield_mode: "gmx",
  yield_dest: "builders",
}

export const arbitrumCommunity: Community = {
  id: "demo-arbitrum-builders",
  name: "Arbitrum Builders",
  description: "Buildathon crews, sponsored houses and on-chain events — all in one place.",
  image_url: "https://znigxxyicqfuzdtdqdin.supabase.co/storage/v1/object/public/hacker-house-images/did:privy:cmpqi7dsz00z50cjot0qaty8u/451abbc2-72f2-4fce-9b6f-1d14cedbdfd8.jpeg",
  category: "Infrastructure",
  city: "London",
  country: "United Kingdom",
  creator: { id: "048c5f94-d50b-4330-bd8f-eaad6f3efb96", handle: "dex", archetype: "builder", avatar_url: "/cypher-kitten/cat-01.gif" },
  member_count: 248,
  is_member: true,
  is_verified: true,
  is_featured: true,
  featured_order: 1,
  verification_requested: false,
  featured_requested: false,
  is_worldwide: false,
  created_at: "2026-06-01T00:00:00Z",
}
