export const COUNTRIES_CITIES: Record<string, string[]> = {
  Argentina: ["Buenos Aires", "Córdoba", "Mendoza", "Rosario"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth"],
  Brazil: ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Curitiba"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary"],
  Chile: ["Santiago", "Valparaíso", "Medellín"],
  China: ["Beijing", "Shanghai", "Shenzhen", "Hangzhou"],
  Colombia: ["Bogotá", "Medellín", "Cali", "Cartagena"],
  "Czech Republic": ["Prague", "Brno"],
  Denmark: ["Copenhagen"],
  Dubai: ["Dubai"],
  Estonia: ["Tallinn"],
  France: ["Paris", "Lyon", "Marseille", "Bordeaux"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"],
  India: ["Bangalore", "Mumbai", "Delhi", "Hyderabad", "Pune", "Chennai"],
  Indonesia: ["Jakarta", "Bali", "Surabaya"],
  Israel: ["Tel Aviv", "Jerusalem", "Haifa"],
  Italy: ["Rome", "Milan", "Florence", "Turin"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Fukuoka"],
  Kenya: ["Nairobi", "Mombasa"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Cancún"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague"],
  "New Zealand": ["Auckland", "Wellington"],
  Nigeria: ["Lagos", "Abuja", "Ibadan"],
  Norway: ["Oslo", "Bergen"],
  Peru: ["Lima", "Cusco"],
  Philippines: ["Manila", "Cebu"],
  Poland: ["Warsaw", "Krakow", "Wroclaw"],
  Portugal: ["Lisbon", "Porto"],
  Romania: ["Bucharest", "Cluj-Napoca"],
  Russia: ["Moscow", "St. Petersburg"],
  Singapore: ["Singapore"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban"],
  "South Korea": ["Seoul", "Busan", "Incheon"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Davos"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket"],
  Turkey: ["Istanbul", "Ankara"],
  UAE: ["Dubai", "Abu Dhabi"],
  UK: ["London", "Manchester", "Edinburgh", "Birmingham"],
  Ukraine: ["Kyiv", "Lviv", "Kharkiv"],
  Uruguay: ["Montevideo"],
  USA: [
    "New York",
    "San Francisco",
    "Los Angeles",
    "Miami",
    "Austin",
    "Denver",
    "Seattle",
    "Boston",
    "Chicago",
    "Las Vegas",
    "Nashville",
    "Portland",
    "Atlanta",
    "Houston",
    "Washington DC",
  ],
  Venezuela: ["Caracas"],
  Vietnam: ["Ho Chi Minh City", "Hanoi", "Da Nang"],
}

export const COUNTRY_LIST = Object.keys(COUNTRIES_CITIES).sort()
