export const queryKeys = {
  profile: "profile",
  builderProfile: "builder-profile",
  hackSpaces: "hack-spaces",
  hackSpace: "hack-space",
  hackSpaceApplications: "hack-space-applications",
  hackerHouses: "hacker-houses",
  hackerHouse: "hacker-house",
  hackerHouseApplications: "hacker-house-applications",
  friendships: "friendships",
  friendshipStatus: "friendship-status",
  notifications: "notifications",
  unreadNotificationCount: "unread-notification-count",
  builders: "builders",
  mapMarkers: "map-markers",
  communities: "communities",
  community: "community",
}
